### ISSUE TITLE
Clarification about project description

### ISSUE THREAD

**Issue by Rudolchr** [tiadal/freeopengym.com#1]
Hello team of freeandopengym,

I would like to ask you, if you could clarify a few points in your projects description:

By Event and classes do you mean

* course (like Yoga course) = Event
* lessons (single session of the Yoga course, frequently on specified dates like each Monday 9 am - 11 am) = Classes

or something else?

What do you expect to happen by the un/follow interaction?
Should there be a notification send to all following users each time when a user joins a new course?
Is this just to see which courses a person offers?

Greetings

**Comment by tiadal** [comment]
Hello,

1. Yes, we do mean that. For example, Max is really good at football and basketball. He can organize 2 events, one for each sport. Each event will have one or more classes per week.

2. It was not clear indeed. People who attend classes can follow teachers. The idea was to have on the homepage a list of new events/classes from teachers we are following. A notification system could be good too if you can implement it as an extra feature.  Following/unfollowing could just change the total number of "followers" on the teacher's profile.

Best Regards
